"""del slug add ccom

Revision ID: cb9f8e321f29
Revises: de3a9cb662d4
Create Date: 2019-03-24 17:54:52.190897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9f8e321f29'
down_revision = 'de3a9cb662d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post') as batch_op:
        batch_op.add_column(sa.Column('can_comment', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('uq_post_slug', type_='unique')
        batch_op.drop_column('slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post') as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=40), nullable=True))
        batch_op.create_unique_constraint('uq_post_slug', ['slug'])
        batch_op.drop_column('can_comment')
    # ### end Alembic commands ###
