"""add slug

Revision ID: de3a9cb662d4
Revises: 3e75201aa606
Create Date: 2019-03-24 17:51:14.837121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3a9cb662d4'
down_revision = '3e75201aa606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post') as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=40), nullable=True))
        batch_op.create_unique_constraint(op.f('uq_post_slug'),['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post') as batch_op:
        batch_op.drop_constraint(op.f('uq_post_slug'), type_='unique')
        batch_op.drop_column('slug')
    # ### end Alembic commands ###
